### ISSUE TITLE
Compatibility with frontier

### ISSUE THREAD

**Issue by EDUARD-EASY** [gautamdhameja/substrate-validator-set#13]
Hello everyone,

I'm trying to install this pallet at frontier: https://github.com/paritytech/frontier, but I have problem of versions.
Is there any manual to install the validator-set at frontier?

Thank you!

**Comment by gautamdhameja** [comment]
Please use the `frontier` branch to use this pallet with the current frontier build. This is a stop-gap solution while frontier is being updated to the latest Substrate tag/release. After that, you can just use the master or latest tag of this pallet.

https://github.com/gautamdhameja/substrate-validator-set/tree/frontier

**Comment by NukeManDan** [comment]
https://github.com/NukeManDan/frontier-template-with-validator-set/blob/main/utils/testnet-instructions.md

This separate repo is a working frontier template with the validator set pallet included, and this file is instructions on use based on the demo video in the pallet README in this repo.

I must mention that we will not maintain this repo, and it is only a stop-gap solution to get you started with a working base frontier node plus the pallet here.
