### ISSUE TITLE
Frontier branch readme

### ISSUE THREAD

**Issue by EDUARD-EASY** [gautamdhameja/substrate-validator-set#15]
Hello @gautamdhameja,

First of all thanks for the new branch frontier.

I'm trying to install the pallet but I can't and the README is not actualized to use the frontier.

Regards.

**Comment by gautamdhameja** [comment]
For using it with the [frontier node](https://github.com/paritytech/frontier/), create a node-template using the [node-template-release script](https://github.com/paritytech/frontier/blob/master/.maintain/node-template-release.sh), and then add this pallet as per the instructions in the readme.
