### ISSUE TITLE
Add a validator without the Account

### ISSUE THREAD

**Issue by EDUARD-EASY** [gautamdhameja/substrate-validator-set#18]
Hello to everyone,

I'm trying to use the pallet without having the account of the node i want to validate.

I'm doing it in 3 steps.

Step 1:  The node who want the validation use rotateKey.

Step 2: Then the same node use setKey to set the new Key.

Step 3: The admin node with sudo use the command setValidation to validate it.

The problem is at the step 3, using polkadot js interface i need to have added the account of the node to select it. I think there should be a way to add a validator without having to add the account.

Regards!

**Comment by gautamdhameja** [comment]
We need some way to identify a validator, and for that we are using AccountId in this pallet. At the moment, there is no way around this. Without a proper identification of validators, we cannot track and manage them in the validator set.
