### ISSUE TITLE
Dev/Test node crashes at startup

### ISSUE THREAD

**Issue by stiiifff** [gautamdhameja/substrate-validator-set#30]
Single node crashes at startup with simple dev / test chain spec (based on Substrate node template).

I'm seeing the following messages in the logs:
```
2021-11-12 10:57:15.053 DEBUG main runtime::validator-set: Initiated removal of 0 offline validators.

2021-11-12 10:57:15.053 DEBUG main runtime::validator-set: New session called; updated validator set provided.

...

Thread 'main' panicked at 'Empty validator set for session 0 in genesis block!'
```

**Comment by gautamdhameja** [comment]
You need to add the validator_set pallet before the session pallet in `construct_runtime`.
From the readme:
> Also make sure that the validator_set pallet is added before the session pallet, because it provides the initial validators at genesis, and must initialize first.
