### ISSUE TITLE
Is it possible to integrate this pallet to a PoA network after genesis?

### ISSUE THREAD

**Issue by arthur-cw** [gautamdhameja/substrate-validator-set#36]
I would like to add more validators to a PoA network already on production. It has the sudo pallet, but not the node-authorization pallet.
Can this pallet be added with a regular runtime upgrade?

**Comment by gautamdhameja** [comment]
Yes, you should be able to add this pallet as part of a runtime upgrade. You would need to write a storage migration to populate the genesis config storage entries for the pallet. 

See the storage migration section here  https://docs.substrate.io/main-docs/build/upgrade/

**Comment by farazahmadvaival** [comment]
@gautamdhameja can you please guide which pallets need to be initialized or resettled during migration?
