### ISSUE TITLE
Version the pallet and name the branches the same way Substrate does

### ISSUE THREAD

**Issue by armyhaylenko** [gautamdhameja/substrate-validator-set#38]
## The problem

`substrate-validator-set` is versioned differently from Substrate pallets. As we know, Substrate follows `polkadot` releases and is versioned like `polkadot-vX.Y.Z`, whereas this pallet does not have the `polkadot-v` prefix present.

## The solution

Please name the branches as `polkadot-vX.Y.Z` and replace the version in Cargo.toml with `4.0.0-dev` until future releases.

**Comment by gautamdhameja** [comment]
More recent tags are named accordingly to Polkadot releases.
