### ISSUE TITLE
error[E0152]: duplicate lang item in crate `sp_io` (which `sp_application_crypto` depends on): `panic_impl`.

### ISSUE THREAD

**Issue by PoCk3T** [gautamdhameja/substrate-validator-set#44]
Trying to follow instructions on the README of https://github.com/gautamdhameja/substrate-validator-set/tree/0.9.27 to the letter, I made it ( = my testnet is running successfully) as far as adding validator_set and session pallets in construct_runtime macro, but as soon as I do that, I'm hitting the following error:

```
error[E0152]: duplicate lang item in crate `sp_io` (which `sp_application_crypto` depends on): `panic_impl`.
spiderweb-chain  |     |
spiderweb-chain  |     = note: the lang item is first defined in crate `sp_io` (which `frame_support` depends on)
spiderweb-chain  |     = note: first definition in `sp_io` loaded from /var/www/spiderweb-node/target/release/wbuild/spiderweb-substrate-runtime/target/wasm32-unknown-unknown/release/deps/libsp_io-fe88ca4604be2dc1.rmeta
spiderweb-chain  |     = note: second definition in `sp_io` loaded from /var/www/spiderweb-node/target/release/wbuild/spiderweb-substrate-runtime/target/wasm32-unknown-unknown/release/deps/libsp_io-7c9d8c555f100c9a.rmeta
```

It's not exactly clear to me if this is a compatibility issue trying to use this pallet on a Polkadot-v0.9.28 node template, or else?

Thank you for your insights @gautamdhameja

**Comment by GabrielMartinezRodriguez** [comment]
Hello PoCk3T, I hope you're doing well. I saw your post in the issue and was wondering if you could share how you resolved the problem. I am trying to understand this same issue in my own project and I believe your experience could be very helpful. Thank you so much for your time and collaboration.

**Comment by gautamdhameja** [comment]
Hey both, this issue could happen when there is a version mismatch between your node-template and the pallet. Try using the same version for both and rebuild after deleting the cargo.lock.

**Comment by gautamdhameja** [comment]
Confirming this is not reproducible.

**Comment by PoCk3T** [comment]
Thanks all for the feedback, I've indeed learned to remove cargo.lock and every other caches files as part of my development process
