### ISSUE TITLE
Automatically add again previously offended validators

### ISSUE THREAD

**Issue by rinat-kharisov-dataart** [gautamdhameja/substrate-validator-set#47]
First, I would like to thank you for your great efforts. 

We use the pallet `validator-set` together with the `im-online` pallet to remove offline validators. It works perfectly. Currently, I'm looking for a way to add an online validator back automatically as soon as it is online. As far as I understand there is no such way due to the `im-online` pallet is not designed to send heartbeats of the validator after being online back. 

So my question: is there any way to call extrinsic `ValidatorSet::add_validator_again` automatically as soon as the validator is online back?

**Comment by gautamdhameja** [comment]
Thanks, @rinat-kharisov-dataart. I wrote about adding online validators back here - https://www.gautamdhameja.com/resilient-poa-network-substrate/. You can look at the last section of that blog post where I have shared some thoughts on the topic. Let me know what you think.
