### ISSUE TITLE
Blocks stop finalising after validator set updated

### ISSUE THREAD

**Issue by kylezs** [gautamdhameja/substrate-validator-set#5]
I was following the youtube guide linked in the README and everything seems to work up until block finalisation.

When I submit the add validator call, that validator shows up in the authority list, and shows that there is an extra validator in the `grandpa.NewAuthorities` event on `recent events`. The new "validator" now starts authoring blocks according to the block explorer, however, the logs of that node just show that it's importing, and also, finalisation just stops after that. Even after removing that validator, which should return the validator set to the original set which was finalising blocks, it still produces blocks, but nothing is being finalised.

**Comment by kylezs** [comment]
After I used custom keys, rather than `--alice` or `--bob` it worked fine.

**Comment by jonathanxuu** [comment]
> After I used custom keys, rather than `--alice` or `--bob` it worked fine.

Met the same problem (the new added validator can't finalize any block).
Does `custom keys` means start a chain with `--node-key <ed25519>` and `--chain ./customSpecRaw.json` ? Appreciate it if you could elaborate the way how to avoid this problem in detail .THX~
