### ISSUE TITLE
Is it possible to start a substrate BABE blockchain with no Grandpa authorities and BABE validators? 

### ISSUE THREAD

**Issue by stackphysics** [gautamdhameja/substrate-validator-set#50]
Hello
I'm trying to implement a PoS network on substrate using substrate provided pallets - pallet_session, pallet_staking, pallet_babe, etc. The current Runtime and chain spec implementation is similar to what is found in the [substrate repository](https://github.com/paritytech/substrate/tree/master/bin/node). I've realized that I need to set Session keys for GenesisConfig before starting the blockchain. I also noticed that the Session keys set for SessionConfig are used to configure the grandpa authorities.

My questions are:

Is there a way to start the blockchain such that no session keys are set?

Do all grandpa authorities need to be hardcoded in the chain spec? If not, how are the authorities added after nodes have gone live?

**Comment by gautamdhameja** [comment]
I think this question is not directly related to this pallet. Please ask your question on Substrate StackExchange and you will be able to get an answer much faster - https://substrate.stackexchange.com/
